<?php

namespace App;

use App\Collections\TaskCollection;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    public function taskable()
    {
        return $this->morphTo();
    }

    public function newCollection(array $models = [])
    {
        return new TaskCollection($models); // TODO: Change the autogenerated stub
    }

    protected $fillable = ['title','description','deadline_date','user_id'];

    public function between()
    {
        $now = Carbon::now()->setTime('00', '00', '00');
        $week = Carbon::now()->addWeek()->setTime('23', '59', '59');
        if ($now < $this->deadline_date && $this->deadline_date < $week) {
            return true;
        }

        return false;
    }
}
